[[introduction]]

== Introduction

The Erlang GraphQL system allows you to implement GraphQL servers in
Erlang. It works as a library which you can use on top of existing web
servers such as Cowboy, Webmachine, Yaws and so on.

As a developer, you work by providing a _schema_ which defines the
query structure which your server provides. Next, you map your schema
unto Erlang modules which then defines a binding of the two worlds.

Clients execute _queries_ to the server according to the structure of
the schema. The GraphQL system then figures out a _query plan_ for the
query and executes the query. This in turn calls your bound modules
and this allows you to process the query, load data, and so on.

=== On this tutorial

The tutorial you are now reading isn't really a tutorial per se where
you type in stuff and see the output. There is a bit too much code for
that kind of exposition. Rather, the tutorial describes a specific
project implemented by means of the GraphQL system. You can use the
ideas herein to build your own.

There are examples of how things are built however, so you may be able
to follow along and check out the construction of the system as a
whole. Apart from being a small self-contained functional GraphQL
project, it is also a small self-contained functional rebar3 project.
So there's that.

Most of the source code in this tutorial refers inside the real source
code. If a section doesn't make sense anymore because the underlying
code has changed, please submit a bug report.

Another kind of bug report we are interested in, are "`I tried doing
this, but the result was not what I expected`". These often indicate
an omission on our part which should have been included.

=== Prerequisites

Some Erlang knowledge is expected for reading this guide. General
Erlang concept will not be explained, but assumed to be known.
Furthermore, some knowledge of the web in general is assumed. We don't
cover the intricacies of HTTP 1.1 or HTTP/2 for instance.

This tutorial uses a couple of dependencies:

* Rebar3 is used to build the software
* Cowboy 1.x is used as a web server for the project
* GraphiQL is used as a web interface to the Graph System
* Erlang/OTP version 19.3.3 was used in the creation of this tutorial

=== Supported Platforms

The GraphQL system should run on any system which can run Erlang. The
library does not use any special tooling, nor does it make any
assumptions about the environment. If Erlang runs on your platform,
chances are that GraphQL will too.

=== License

MIT 2.0

----
Copyright (c) 2016-2017, Shopgun Aps
----
